fix tests

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -1,5 +1,5 @@
 # The name of the workflow. GitHub displays the names of your workflows under your repository's "Actions" tab. If you omit `name`, GitHub displays the workflow file path relative to the root of the repository.
-name: Java CI
+name: CI
 
 #
 on:
@@ -32,9 +32,20 @@ jobs:
           distribution: 'corretto'
       # The "Build with Maven" step runs the Maven `package` target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
       - name: Build with Maven
-        run: mvn clean install test
-      - name: Report
-        uses: dorny/test-reporter@v1
+        run: mvn clean install
+
+      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
+#      - name: Update dependency graph
+#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v1
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/build/test-results/test/TEST-*.xml'
+#      - name: Run JUnit Tests
+#        run: mvn test
+      - name: JUnit Test Report
+        uses: dorny/test-reporter@v1 #{owner}/{repository}@{ref}
         if: always()
         with:
           name: Maven Tests
